#!/bin/bash

# Python artefacts
find "$(dirname "${0}")" -name '__pycache__' -print0 | xargs -0 rm -rf 2>/dev/null
rm -rf "$(dirname "${0}")"/{MANIFEST,build,dist,.pybuild}

# Debian artefacts
rm -rf "$(dirname "${0}")"/*.{deb,buildinfo,changes}
rm -rf "$(dirname "${0}")"/debian/{.debhelper,debhelper-build-stamp,files,tmp}
rm -rf "$(dirname "${0}")"/debian/*.debhelper.log
rm -rf "$(dirname "${0}")"/debian/*.substvars
# (package-specific)
rm -rf "$(dirname "${0}")"/debian/{gcfg,gcfg-python3}
