#!/bin/bash

# Ansible artefacts
find "$(dirname "${0}")" -name '*.retry' -delete
rm -rf "$(dirname "${0}")"/gcfg-gcfg-*.tar.gz

# Python artefacts
find "$(dirname "${0}")" -name '__pycache__' -print0 | xargs -0 rm -rf 2>/dev/null
rm -rf "$(dirname "${0}")"/{MANIFEST,ansible_collections_gcfg.gcfg.egg-info,build,dist,.eggs,.pybuild}

# Debian artefacts
rm -rf "$(dirname "${0}")"/*.{deb,buildinfo,changes}
rm -rf "$(dirname "${0}")"/debian/{.debhelper,debhelper-build-stamp,files,tmp}
rm -rf "$(dirname "${0}")"/debian/*.debhelper.log
rm -rf "$(dirname "${0}")"/debian/*.substvars
# (package-specific)
rm -rf "$(dirname "${0}")"/debian/gcfg-ansible
